### ISSUE TITLE
Error While Patching on Android 6.0

### ISSUE THREAD

**Issue by Coffeelatte369** [kitadai31/revanced-patches-android6-7#1]
### Type

Error while patching

### Bug description

Hello, just like the title, i got the error while patching youtube apk. I'm using an old android with android 6 or 7 so i came here to use your app. I have followed all the procedure and everything was alright until halfway, and suddenly it's error like the screenshots below. And now it's aborting instead patching, could you answer or fix it please? Thanks a bunch!
![339745486_234174775832821_7794793368304987657_n](https://user-images.githubusercontent.com/111590878/232193515-5840c6ed-e2d3-44c9-a12f-6aea5c74770b.jpg)
![339547509_1398071697678185_1676525983522664396_n](https://user-images.githubusercontent.com/111590878/232193527-e3c807d0-85e3-4e8d-9017-cdae9fcf9884.jpg)

### Steps to reproduce

Yes i followed all the steps.

### Relevant log output

```shell
Already put it on desc
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by d4n3436** [comment]
Hey, I managed to create a working patched YouTube APK using the [manager provided by the author](https://github.com/kitadai31/revanced-manager-android6-7), the custom sources in the readme, the base 17.34.36 APK from [APKMirror](https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-34-36-release/youtube-17-34-36-2-android-apk-download/) and Vanced MicroG from [here](https://github.com/inotia00/VancedMicroG/releases/tag/v0.2.27.230755).

Make sure you're patching the app with a minimal selection of patches. I used the following and YouTube works fine so far:
- Client Spoof
- Protobuf Spoof
- Hide General Ads
- Hide Video Ads
- MicroG Support
- Sponsorblock
- Return Youtube Dislike

This works for me on Android 7. Not sure if it'll work on Android 6.

**Comment by kitadai31** [comment]
My Manager does not seem to work well in Android 6.0. My apologies.

I just released a new version of the patch, including fix for Android 6.0.
Could you test it again?
Please clear the app data of ReVanced Manager in app info before patch again.

**Comment by alcatraz-zz** [comment]
Could you link to an apk for download perhaps? I haven't had much luck with the manager.

The last patched 17.34.36 I tried had a 1min playback interruption problem that no other vanced version I tried had.

**Comment by alcatraz-zz** [comment]
I can't believe it worked! Thank you. I'm helping others to find your work. I just posted a guide on xda. Starred!

I would have saved a TON of time if it was a bit more clear that I shouldn't manually select patches. Just tick "recommended". Man, I wasted 1 hour reading up on all the patches. I patched 4 times on my slow phone before I figured out "recommended".

**Comment by alcatraz-zz** [comment]
> @alcatraz-zz
> 
> > Could you link to an apk for download perhaps?
> 
> I do not. It's dangerous.
> 
> > I haven't had much luck with the manager.
> 
> Manager currently unavailable on Android 6.0, sorry. https://github.com/kitadai31/revanced-manager-android6-7#it-may-not-work-on-android60
> 
> Please use newer device. If you don't have, use ReVanced Builder. https://github.com/kitadai31/revanced-patches-android6-7/wiki/How-to-build#method-3-using-revanced-builder If you have trouble in these ways, please open a new Issue or Discussion.

I got a quick quesion. When using the recommended patches, what version is it now spoofed as? I'm curious because I'd like to have it working for as long as possible.

**Comment by kitadai31** [comment]
@alcatraz-zz Please open new question in GitHub Discussions.
Annoyance emails are sent to unrelated participants.

**Comment by Coffeelatte369** [comment]
I've tried the third way which to patch a youtube apk via PC revanced builder (since my phone also cant open termux via f-droid, and it's work so far for my android 6. I'm closing this thread.
