### ISSUE TITLE
Videos stops working after around 60 seconds

### ISSUE THREAD

**Issue by DestinoLol** [kitadai31/revanced-patches-android6-7#11]
### Type

Error while patching

### Bug description

I'm trying the yt version with spoofing and all the videos stops working after 60 seconds can you patch?

### Steps to reproduce

Download dark spoofing version and then try it

### Relevant log output

```shell
No logs
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by evd316** [comment]
> 

Enable>RebootApp>Disable>RebootApp>Enable
