### ISSUE TITLE
bug: error while patching

### ISSUE THREAD

**Issue by I-like-Portal-2** [kitadai31/revanced-patches-android6-7#12]
### Type

Error while patching

### Bug description

Hi, when I try to patch youtube (the 17.34.36 version), there is an error every time i try to patch. I have MicroG, and I selected MicroG support (no root), and i still get this error. what can i do? is it my fault?

### Steps to reproduce

Step 1. Select the youtube from storage
Step 2. Apply some patches
Step 3. Press start
Step 4. Enjoy

### Relevant log output

```shell
See screenshot below (sorry, it doesn't copy)
```

### Screenshots or videos

![WhatsApp Image 2023-04-20 at 17 22 08](https://user-images.githubusercontent.com/99472757/233396587-a23227c6-37aa-462a-b046-a44533477759.jpeg)

### Additional context

sorry if i'm being dumb.

oh yeah, my device is Huawei MediaPad T3 10. Android 7.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
It is original ReVanced Manager's issue
probably it's a temporary bug
