### ISSUE TITLE
The new interface plugin has a problem with the description bug: <title>

### ISSUE THREAD

**Issue by Paplock** [kitadai31/revanced-patches-android6-7#18]
### Type

Cosmetic

### Bug description

The bug is based on the experimental design of the new interface for YouTube's recent Nougat update. The problem is that sometimes when I click on the description it freezes and there is an error that the application has stopped. Sometimes it doesn't happen, but when I disabled the plugin, I still have a problem sometimes and I can't go back to classic YT style (old). Application created by myself, without other third parties

### Steps to reproduce

![_20230422_170532](https://user-images.githubusercontent.com/85745525/233792727-e0fd436a-fb04-4c4e-b239-9ff7cff5cb99.JPG)
![_20230422_170513](https://user-images.githubusercontent.com/85745525/233792728-9445c5f9-f571-4359-80a8-8f4a06f1860e.JPG)

### Relevant log output

```shell
.
```

### Screenshots or videos

![_20230422_170532](https://user-images.githubusercontent.com/85745525/233792586-f9095ff2-70d6-43cc-8462-f7b8965e4b47.JPG)
![_20230422_170513](https://user-images.githubusercontent.com/85745525/233792588-ead6daa5-fbea-4eb9-a3d3-0afe7dc9c8b5.JPG)

### Solution

Possibly some you need to use (Clear all app data). You can add that you enable the interface plugin for a while and then disable it, but it works for a while.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
It takes time to recieve old layout from server. (several hours)
So that setting does not reflect immediately.
If you want old layout immediately, you have to clear app data.

> The problem is that sometimes when I click on the description it freezes and there is an error that the application has stopped.

It's reproducible. thanks.

**Comment by kitadai31** [comment]
marge to https://github.com/kitadai31/revanced-patches-android6-7/issues/10
