### ISSUE TITLE
feat(patch): "Enable old layout" patch

### ISSUE THREAD

**Issue by IMX-Otaku** [kitadai31/revanced-patches-android6-7#19]
### Application

YouTube

### Issue

This patch should fix the bug with the button container in the old layout enabled by account side.
![Screenshot_20230423-163416_ReVanced Extended](https://user-images.githubusercontent.com/95895413/233911250-f1277032-6c3e-4fa7-a5b9-5cecf60beb64.jpg)

### Patch

The same patch that is in og ReVanced Extended. This patch is intended for the users that have the new layout design enabled by account side.
The patch should change (spoof) the version of the application to an older one.

### Motivation

Some users would like to switch between the new and old layout without having to keep changing the "spoof version" option in options.toml over and over again.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
Added in [v2.160.4](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.4)

(Button container bug in 17.34.36 had already been fixed by server-side.)
