### ISSUE TITLE
bug: crash immediately

### ISSUE THREAD

**Issue by iexa** [kitadai31/revanced-patches-android6-7#21]
### Type

Other

### Bug description

Using an older lenovo tablet that is x86_64 processor based, exact type: YB1-X90F, it is on android 7.1.1 (api 25 if I am right). The official youtube 17.34.36 release runs mostly fine (sometimes, rarely, it also freezes but not right upon launch). 

Then vanced microg latest version was installed ( 0.2.27.231515 ), I also managed to set up the login inside this.

So once patches are applied (recommended, but I tried without the one theme patch removed - that I read somewhere could probably help, still same issue) and original youtube app uninstalled, revanced  installed, app launches and immediately quits.

What could it be? Maybe the patcher does not patch the x64 library files? Can you suggest some ideas what I could look at?

Or maybe some patches that might effect the freeze?

Anyway where is the patched apk saved?

thx,

### Steps to reproduce

Nothing, just offical steps, and recommended patches.

### Android version

7.1.1

### Manager version

the one from here

### Target app name

default one recommended

### Target app version.

17.34.36

### Installation type

Non-root

### Patches selected.

recommended ones only, also tried with them theme patch removed, same.

### Device logs (exported using Manager settings).

```shell
no issue with manager, the patched app freezes
```

### Screenshots or videos

immediate quit, so no scrshot

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by kitadai31** [comment]
(Moved from Manager repo to Patches repo.)

Try old microG? (not mMicroG)
https://github.com/inotia00/VancedMicroG/releases/tag/v0.2.27.230755

**Comment by Lerbiq** [comment]
I've got the exact same issue and the same hardware.

Without adding an account to MicroG everything works fine. But once you add the account in the app, it crashes immediately. Adding it outside the app doesn't have a different outcome, ReVanced crashes once it's launched.

I've also tried the MicroG linked above and several other versions, all with the same issue. I'm not completely sure if it indeed is an issue with MicroG or with the ReVanced app freaking out from the account being added.

**Comment by TheRaphael0000** [comment]
Hi before I used the right revanced-integrations apk I had the same issue: Compilation was fine, but couldn't run the app. Even when just using microg and client-spoof.

The right one: https://github.com/kitadai31/revanced-integrations/releases/tag/v0.96.7
The one I was using this one: https://github.com/ReVanced/revanced-integrations/releases/tag/v0.96.2

Maybe you did the same mistake, I don't know. Hope it can help

**Comment by TheRaphael0000** [comment]
@kitadai31 Can you add these links to the wiki for building with the CLI (Method 5) ? I don't know how to do PR on wikis, sry...
```
CLI:
https://github.com/ReVanced/revanced-cli/releases/tag/v3.1.1

Revanced-integrations:
https://github.com/kitadai31/revanced-integrations/releases

Patches:
https://github.com/kitadai31/revanced-patches-android6-7/releases
```
This might help people to clarify exactly which version to use, since 0.96.x can be either the offical revanced-integration release or yours

**Comment by kitadai31** [comment]
> Can you add these links to the wiki for building with the CLI (Method 5) ? I don't know how to do PR on wikis, sry...

done
