### ISSUE TITLE
bug: No buttons at the bottom.

### ISSUE THREAD

**Issue by Vansh1304** [kitadai31/revanced-patches-android6-7#24]
### Type

Other

### Bug description

The bug is about the UI. It doesn't have the buttons at the bottom like Home, Shorts, (+), subscriptions and library. As I'm an Android user, I cannot provide screenshots by dragging and dropping. 

### Steps to reproduce

I don't know exactly how to reproduce this bug but I can still try:-
What I did was:- 
-I borrowed someone else's phone (Android 13),
-Went to Sources option, and everything mentioned in the guide, 
-During Patching I selected all the 69 patches and clicked on patch button,
-In the logs, everything was applied successfully and no error was found,
-Then I exported the apk and send it to my Android 6 device and then installed it. 

### Device Environment

Android 6.0.1, FuntouchOS (Vivo) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
Are you the poster of these issue screenshots?
https://cdn.discordapp.com/attachments/952946952348270626/1101510051388198963/Screenshot_20230428_193608.jpg
https://cdn.discordapp.com/attachments/952946952348270626/1101747894236753960/Screenshot_20230429_112216.jpg

Do not select all patches.
Tap the "Recommended" button please.

**Comment by Vansh1304** [comment]
Yes, I'm the poster of those screenshots,


Recommend patches only including custom name patch, 3x Spoofing patches,
and a premium header icon patch. All the rest are showing a Warning Sign.

**Comment by kitadai31** [comment]
It's weird.
Make sure you are using the recommended version APK.

https://github.com/kitadai31/revanced-patches-android6-7/wiki/How-to-build
Linked from this page.

**Comment by Vansh1304** [comment]
I'm using the recommended version (v17.34.36)

**Comment by kitadai31** [comment]
Try delete temporary files of Manager

Manager > Settings > Delete temporary files

Then restart manager

**Comment by Vansh1304** [comment]
Alright, lemme see. I'll get back to you after re-patching Re-Vanced with
the above method too.

**Comment by Vansh1304** [comment]
Patched, no errors in logs. But same issues with the UI

**Comment by Vansh1304** [comment]
Can you patch it and provide me an apk file? I'll be very thankful to you
if you do so.

**Comment by kitadai31** [comment]
I just released the new version of patches. (v2.160.4)
Please try again with the new version.

If you use Manager, swipe down in Dashboard page to update patches.
Or possibly you have to clear the app data of Manager.

**Comment by Vansh1304** [comment]
Hi, It finally worked out. And I wanna say that, no bug was found. I did
applied not only the recommend ones, but all the patches available in
manager and they worked flawlessly without any issues.
But this whole process of applying patches took more than 4 hours in my
Low-end phone but I think it was worth the effort.

I'm currently using the layout of version 18.05.40 (spoofed) and no crashed
occurred during opening large descriptions (as mentioned in the warning
sign in settings of revanced)


Once again, Thank You for the support.



  Best regards,
- Vansh Bhatia

**Comment by kitadai31** [comment]
I'm glad to hear that.

Tips: I don't recommend select multiple "Custom Branding XXX" patches.
There is no point in applying multiple of those patches.
And applying those patches is very time consuming.
Choose one of them.

Also, Revancify is much faster than ReVanced Manager. I recommend Revancify.
(However, Termux uses a lot of storage, so it may be difficult for phones with limited space.)

**Comment by Vansh1304** [comment]
Thanks for the additional Tips too. I've skill issues as you know.



Can I have Revancify's Guide link too? (In case of building apk again)

**Comment by kitadai31** [comment]
guide is here
https://github.com/decipher3114/Revancify

During installation, you will be prompted to select several times, follow the statement "Default = N" and press N.
