### ISSUE TITLE
feat(patch): Rest for Korean Translation

### ISSUE THREAD

**Issue by ZeroZero0011** [kitadai31/revanced-patches-android6-7#26]
### Application

RVX for android 6-7

### Issue

I want to translate the rest into Korean, but is it possible to get the syntax IDs that are not in the string.xml?

### Patch

No

### Motivation

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
possible.
just add a new `<string name=""></string>` element.

**Comment by ZeroZero0011** [comment]
i dont know string name....

**Comment by kitadai31** [comment]
Search in https://github.com/kitadai31/revanced-patches-android6-7/blob/revanced-extended/src/main/resources/youtube/settings/host/values/strings.xml

If you cannot find it in this file, I don't know...

**Comment by ZeroZero0011** [comment]
thanks

i saw string.xml in patch.jar file.
