### ISSUE TITLE
bug:  Return Youtube Dislike and SponsorBlock is not working

### ISSUE THREAD

**Issue by rexrey** [kitadai31/revanced-patches-android6-7#29]
### Type

Error at runtime

### Bug description

ReturnYoutubeDislike and SponsorBlock is not working. And I believe its only on my phone i.e. v17.34.36 because I've another phone with official Revanced patches and it's working fine.

### Steps to reproduce

I don't know how.

### Device Environment

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rexrey** [comment]
> I can't reproduce.
> 
> ![Screenshot_20230508-195529](https://user-images.githubusercontent.com/90122968/236810291-84377432-3470-44f2-9f13-3ae2446857c0.png)
> 
> Please try clear app data or reinstall the app.
> If no effect, I think it's temporally server down of RYD and SponsorBlock.

I've done everything. To be honest I'm still using OG YT ReVanced app but when buffering issue started I tried RV extended and other apps on the internet until I found you. Never had any problem with sponsorblock but now it's always stuck on Stats Loading.. (on both apps)
on my device it works on Newpipe x SponsorBlock.

Android v7
I'm using microg 0.2.24.220220
I'm from India.


![sponsorblockpb.jpg](https://user-images.githubusercontent.com/93119375/236873098-5a6761fa-1315-4e22-a14e-d4b4c65a2f82.jpg)

**Comment by rexrey** [comment]
@kitadai31 I went on rampage last night.. tried everything and had my luck with @inotia00 mMicroG app. I was using OG Vanced microg from old days.. I got rid of it and tried others but had buffering issues then I installed mMicroG and now everything running smooth.

**Comment by kitadai31** [comment]
I’m glad to hear that.

By the way, you mentioned inotia00 unintentionally. Be careful.

**Comment by rexrey** [comment]
> I’m glad to hear that.
> 
> By the way, you mentioned inotia00 unintentionally. Be careful.

can we have ambient mode on v17.34.36 by spoofing?

**Comment by kitadai31** [comment]
impossible
