### ISSUE TITLE
bug: Live chat not updating if app version is spoofed

### ISSUE THREAD

**Issue by tesmite** [kitadai31/revanced-patches-android6-7#33]
### Type

Other

### Bug description

English
When the "Spoof App Version" is enabled, Live chat is not updated when a new comment is posted in the chat during a live streaming video.

Japanese / 日本語
"Spoof App Version"を有効にしている場合にライブ配信中の動画にてチャットに新しいコメントが投稿されてもチャット欄が更新されません。

### Steps to reproduce

English
Step 1. Enable "Spoof app version".
Step 2. Watch the live streaming video.
Step 3. open live chat.

Japanese / 日本語
ステップ1. "Spoof app version"を有効にしいずれかのバージョンに偽装します。
ステップ2. ライブ配信中の動画を見ます。
ステップ3.  チャット欄を開きます。

### Solution

English
Correction of chat fetching process in case of version spoofing.

Japanese / 日本語
バージョン偽装時におけるチャット取得処理の修正

### Additional context

English
Comment fetching may proceed normally for a minute or so.
In the case of the live archive, the chat comments are fetched properly from the beginning to the end of the video, so it seems that new comments are not being fetched properly by the automatic update of the chat section in the case of the live chat.
New comments can also be fetched by opening and closing the chat column to reload it.

Japanese / 日本語
1分程度は正常にコメント取得が行われることもあります。
ライブのアーカイブの場合は動画の最初から最後までチャットのコメントが正常に流れるためライブチャットの場合におけるチャット欄の自動更新による新規コメントの取得が正常に行われてないものと思われます。
チャット欄の開閉で再読み込みを行うと新しいコメントも取得できます。

### Device Environment

Devices / デバイス
Samsung Galaxy Note8 SC-01K (Android 9)
Rakuten Hand Tinno P710 (Android 10)
SHARP AQUOS R3 SHV44 (Android 11)

App Version / アプリバージョン
YouTube Revanced 17.34.36 (Revanced Patches v2.160.4)

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
今年の7月から10月くらいの間に何回か旧バージョンに偽装して生配信を視聴してみたところ、その現象が発生するときと発生しないときがありました。
このことから、おそらくYouTubeのサーバーサイドの問題なのでRVXでは対処できなさそうです。
