### ISSUE TITLE
bug: Videos start buffering after 30-70 seconds of runtime

### ISSUE THREAD

**Issue by JuicyJonJoe** [kitadai31/revanced-patches-android6-7#38]
### Type

Error at runtime

### Bug description

Have used this app without any issues for a month, this issue suddenly started yesterday on 26th of July.

Videos will buffer after around 1 minute (differs per video) of runtime no matter what. 
Even if you close the video and reopen it, it happens again.
Youtube livestreams barely play a second before it starts buffering.

I tried disabling the protobuf spoof and it only helps a little bit, livestreams can play for a dozen seconds max now before buffering. Videos show the same issue though, starts buffering after 1 minute ish. Trying to get past the 1 minute mark by dragging the slider also buffers the video.

I have tried uninstalling and reinstalling both YT Revanced and Manager to no avail. Same with disabling and re-enabling protobuf spoof.

### Steps to reproduce

Step 1. Play any video
Step 2. Video starts buffering after around 1 minute.
Step 3. Continues buffering until closing the video.
Step 4. Re-open video -> Step 2.

### Device Environment

Android 7.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnll56** [comment]
Not a bug, it's just that Kitadai hasn't yet implemented the newest patch from the official Revanced team (Signature spoof toggle in Misc settings), which is needed for videos to play correctly. Kitadai tweeted that he will release an updated version of his fork in August.

**Comment by ghost** [comment]
> Not a bug, it's just that Kitadai hasn't yet implemented the newest patch from the official Revanced team (Signature spoof toggle in Misc settings), which is needed for videos to play correctly. Kitadai tweeted that he will release an updated version of his fork in August.

Till then what? Wait?

**Comment by ghost** [comment]
Same happening with me.... unable to watch any video except shorts

**Comment by JuicyJonJoe** [comment]
> Not a bug, it's just that Kitadai hasn't yet implemented the newest patch from the official Revanced team (Signature spoof toggle in Misc settings), which is needed for videos to play correctly. Kitadai tweeted that he will release an updated version of his fork in August.

Thanks for the reply! Will keep this open until it's updated so other people can find out easily.

**Comment by endlessquest** [comment]
hi :)
Same issue, since a couple of days... :(
looking forward for an update.
thanks for the great job you're doing in behalf of us all

**Comment by johnll56** [comment]
> thanks for the great job you're doing in behalf of us all

this!!

**Comment by obiwankenobi7** [comment]
Exactly the same here. It started happening today August 3, a few hours ago. Running on Android 6.0.1. I take using the app perfectly for the last couple of months but it stopped working this afternoon. So I sum myself to the waiting for an update/solution and also take the chance to thank the developers for keeping up the supporting those of us who still have to deal with Android 6 & 7 devices. Thank you!

**Comment by Jarusz** [comment]
Started happening to me too, is there a temporary fix, at least for the videos? Even if it were to load slowly thats better than not working at all...

**Comment by ashutoshsoni2748** [comment]
It started today 3 august that the video is not playing

**Comment by markjoren7** [comment]
the 
/same thing happened to me. when I play any video. It stopped after a few seconds.

**Comment by markjoren7** [comment]
the same thing happened to me. when I play any video, it stops after a few seconds.

**Comment by ghost** [comment]
> Started happening to me too, is there a temporary fix, at least for the videos? Even if it were to load slowly thats better than not working at all...

Switch accounts or go incognito/log out. These are the solution

**Comment by ashutoshsoni2748** [comment]
> > Started happening to me too, is there a temporary fix, at least for the videos? Even if it were to load slowly thats better than not working at all...
> 
> Switch accounts or go incognito/log out. These are the solution

Thanks for temporary solution

**Comment by obiwankenobi7** [comment]
> > Started happening to me too, is there a temporary fix, at least for the videos? Even if it were to load slowly thats better than not working at all...
> 
> Switch accounts or go incognito/log out. These are the solution

This same situation happened back in April, and the solution of switching to another account (specially if it isn't from gmail domain) worked only for a few days, hopefully the solution arrives before.

**Comment by JuicyJonJoe** [comment]
Big thanks to kitadai for the hard work and providing us with the latest patch! Just tried it out, videos work again!! Appreciate you doing this for us.

**Comment by endlessquest** [comment]
kitadai31 for president!!!

**Comment by endlessquest** [comment]
kitadai31 for president ! ! !

**Comment by obiwankenobi7** [comment]
Thank for make revanced great again!
