### ISSUE TITLE
Protobuf error, new issue.

### ISSUE THREAD

**Issue by alcatraz-zz** [kitadai31/revanced-patches-android6-7#39]
Hey fellas

The app has been working great for months. Today however the protobuf stopped working. I tried spoofing to 18.05 17.03 and 17.34 but none worked. They stop buffering after ~60s.

Any ideas?

**Comment by ashutoshsoni2748** [comment]
This happened with me tooo... Today 3 august

**Comment by johnll56** [comment]
Kitadai is working on it. Read the last posted issue and/or the main readme page.

**Comment by kitadai31** [comment]
fixed in [revanced-patches-2.160.5](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.5)

**Comment by alcatraz-zz** [comment]
> fixed in [revanced-patches-2.160.5](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.5)

Thank you so much.

Hey kitadai31. Now that RVX is EOL are there any plans of making these patches work with Revanced? 

Or perhaps there's no need because Android 6-7 users are kind of screwed after 17.34.36 is EOL. Hmm...

**Comment by kitadai31** [comment]
@alcatraz-zz Android 6-7 patch is already using the older RVX (2.160.1, February 13), so it won't effected by RVX's discontinuation.
