### ISSUE TITLE
bug: The app closes after displaying the logo for about 10 seconds.

### ISSUE THREAD

**Issue by johncaiwa** [kitadai31/revanced-patches-android6-7#40]
### Type

Error at runtime

### Bug description

I made the APK on my phone with Android 9.

I selected the default patches, which selected pretty much all of them IIRC.

I downloaded the patched APK onto my Nexus 7 (2013), Android 6.0.1

It installed successfully on the Nexus 7.

However, when I open it, the logo appears for 10 seconds, then the app closes.

I believe my Nexus is still rooted, and Magisk is installed.

### Steps to reproduce

Step 1: Create the patched APK on Android 9.

Step 2: Move the patched APK to the Android 6.0.1 Nexus 7 (2013) device.

Step 3: Install the APK

Step 4: Open the App

### Relevant log output

```shell
None
```

### Device Environment

Android 6.0.1
Nexus 7 (2013)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
MicroG is installed properly?

**Comment by johncaiwa** [comment]
now it is. but that wasn't anywhere in the instructions. it's working now. thanks!
