### ISSUE TITLE
bug: video randomly stops working 

### ISSUE THREAD

**Issue by Nullimw-uaser** [kitadai31/revanced-patches-android6-7#44]
### Type

Other

### Bug description

I watched videos 

### Steps to reproduce

Step 1 enable new layout
Step 2 enable v p 9 codec 

### Solution

Close the video and re open the video do it every 1 min

### Additional context

At first i couldn't watch a video more than 1 min

### Device Environment

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
Already fixed in [v2.160.5](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.5)
