### ISSUE TITLE
bug: all videos stop loading around the 1 minute mark

### ISSUE THREAD

**Issue by rumplee** [kitadai31/revanced-patches-android6-7#49]
### Type

Error at runtime

### Bug description

The title says it all

### Steps to reproduce

Play any video and wait for some time. The videos buffer indefinitely 

### Additional context

I tried enabling and disabling spoofing and re-downloading both the app and microg

### Device Environment

I use a Huawei p9 lite if that helps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
already fixed in v2.160.5
