### ISSUE TITLE
bug: Shorts in Subscriptions tab are not removed [Android 7.0]

### ISSUE THREAD

**Issue by evd316** [kitadai31/revanced-patches-android6-7#5]
### Type

Other

### Bug description

The slider does not remove Shorts in Subscriptions tab, switching it does not work.

### Steps to reproduce

Twisting the slider and reloading does not affect the display of Shorts in Subscriptions tab.

### Relevant log output

```shell
I don't understand, I can't do it
```

### Screenshots or videos

![Screenshot_20230419-131025](https://user-images.githubusercontent.com/65615541/233045053-1698286c-b3e6-4efc-bc17-631d47ce0baf.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
Thank you for waiting.
Fixed in [v2.160.4](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.4)!
