### ISSUE TITLE
feat(patch): Disable update screen

### ISSUE THREAD

**Issue by tesmite** [kitadai31/revanced-patches-android6-7#54]
### Application

YouTube ReVanced

### Issue

Perhaps because Google has ended support for this version, a screen requesting an update appears at startup and is no longer available.
![Screenshot_20231221-003240](https://github.com/kitadai31/revanced-patches-android6-7/assets/111569199/cd79c19c-98a4-4543-bc48-937ad94a5726)

### Patch

Is it possible to disable the update screen?

### Motivation

We probably won't be able to run this app unless we create this patch and turn off the update screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
Currently, users who are using "Spoof app version" setting to spoof to old versions are experiencing this issue.
I'm going to do it.

For now, please clear the app data to reset "Spoof app version" setting and don't use it.

**Comment by tesmite** [comment]
Oh, I am sure that if I did not use the "spoof app version", the update screen would not appear.
I apologise for the inconvenience caused by my lack of research.
It's likely that Google will increase the target for forced updates in the future, so it may be necessary to prepare for that, but it's not essential, at least for now.
