### ISSUE TITLE
bug: Sponsorblock won't load and/or loads very Slowly

### ISSUE THREAD

**Issue by DraconicNEO** [kitadai31/revanced-patches-android6-7#55]
### Type

Other

### Bug description

I installed Revanced Extended on my device since it doesn't support the official Revanced and when I go to play a video the video plays but sponsored segments aren't shown in the bar and they don't get skipped.

I found they do appear if I idle on the SponsorBlock tab in settings until stats appears, which takes a long time.

### Steps to reproduce

Try to play a video on a fresh installation 

### Solution

I don't know how to fix it. Segments appear if I idle on Sponsorblock settings but it's still very slow, which seems like there's a problem with it.

### Device Environment

Android 7.1 FireOS 6.3.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
I think it's your network problem

**Comment by DraconicNEO** [comment]
> I think it's your network problem

It was, sorry I tried on a different network and it worked but I forgot to come back to close this issue.
