### ISSUE TITLE
bug: default-video-quality not working properly with old version spoof

### ISSUE THREAD

**Issue by tesmite** [kitadai31/revanced-patches-android6-7#60]
### Type

Other

### Bug description

When changing the video quality with the "Enable save video quality" option activated, the quality selected does not match the quality set as default, making it unusable under the environment of the old version's image quality selection UI

### Steps to reproduce

Step 1. spoof app version to old version like 16.03.35
Step 2. Enable "Enable save video quality" option
Step 3. Play the video and change the video quality from the options

### Screenshots or videos

https://github.com/d4n3436/revanced-patches-android5/assets/111569199/947654b8-b084-4a98-b847-305c713a75f2

### Additional context

It was previously opened in [ReVanced for Android 5 repo by d4n3436](https://github.com/d4n3436/revanced-patches-android5/issues/15), but it has been moved because it also occurs here.

### Device Environment

Android 12, AQUOS R5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
Google stopped support for 16.01~17.32, so no more needed

![Screenshot_20240227-151002_YouTube](https://github.com/kitadai31/revanced-patches-android6-7/assets/90122968/1c4bc9f2-a4c1-47d1-84be-061ea2e7c851)

古いバージョンでは今とは画質の並び順が逆だったのが原因だったんですかね…　（調べる前に使えなくなったのでわからないですが）

**Comment by tesmite** [comment]
> Google stopped support for 16.01~17.32, so no more needed
> 
> ![Screenshot_20240227-151002_YouTube](https://private-user-images.githubusercontent.com/90122968/312058666-1c4bc9f2-a4c1-47d1-84be-061ea2e7c851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDM0NzgsIm5iZiI6MTcxMDI0MzE3OCwicGF0aCI6Ii85MDEyMjk2OC8zMTIwNTg2NjYtMWM0YmM5ZjItYTRjMS00N2QxLTg0YmUtMDYxZWEyZTdjODUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDExMzI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNjhjMzBlNTI0MjcyY2I4YjM2MTA4Mzc5NDc1M2ZiOTAzMGE2ODljMWZmOWM4YmE2NDU4MDliZTBlYmMzZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3vu4PFDWvj1hR3I9citQVDu0r6bcGYGVtGdCOL44NoM)
> 
> 古いバージョンでは今とは画質の並び順が逆だったのが原因だったんですかね…　（調べる前に使えなくなったのでわからないですが）

忘れていましたがこちらも現行最低バージョンだと既に発生しなくなっていたんですね
やっぱりそこが原因ですかね…なんとなくそんな気はします
