### ISSUE TITLE
bug: watched videos don't get saved properly in history

### ISSUE THREAD

**Issue by jpa102** [kitadai31/revanced-patches-android6-7#63]
### Type

Error at runtime

### Bug description

whenever i watch any long-form videos with **spoof player parameter** on, it doesn't get counted as "watched" in history tab. only videos from shorts appear

by turning it off, watched videos *(no matter the time)* appear in the history

### Steps to reproduce

1. enable spoof player parameter
2. watch any video

### Additional context

this also happens in 16.40.36 *(d4n3436 revanced)*

### Device Environment

android 13, galaxy m12, non-root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
reflected in [revanced-patches-v2.160.8](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.8)
