### ISSUE TITLE
feat(patch): Patch Request for v16.40.35 

### ISSUE THREAD

**Issue by KindlyOnes** [kitadai31/revanced-patches-android6-7#7]
### Application

16.40.35(1523703232)

### Issue

There are no patches for this version of youtube 16.40.35(1523703232).  The Vanced version was for the previous version 16.29.39.  I could use it because of changing the version number to 16.40.35.  However, Vanced is no longer available.  Logging in with an account causes it to ask for an update. Original Youtube app downloaded from Playstore does not want to update.  There is no problem in its working.

### Patch

Just no ads will be enough for me to use in CLI  I can't ask for more at this point.  I've been using Vanced almost since it first came out.  I don't know the difference with the original.

### Motivation

I don't think too many people are using android 5 (sdk:21) right now.  You may not want to patch for very few people.  They said I should try requesting it here on Discord.  I know there are alternative OpenSource youtube apps but they cannot be used with google account.  People like me who can't get a new device or want to use their working device in some way will be really grateful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by d4n3436** [comment]
Hey, I was testing and debugging the patches to add support for Android 5. My changes are in [this repo](https://github.com/d4n3436/revanced-patches-android5).
Currently a minimal selection of patches work, like MicroG support, spoof patches and hide video ads. The patched app seems to work fine (at least on an emulator).
I tried to make the other patches to work but the current repo layout is confusing to work with because it's outdated from upstream.

Command I used to patch YouTube:
```
java -jar revanced-cli.jar -a YouTube_16.40.36.apk -o YouTube_ReVanced_16.40.36.apk -b revanced-patches-2.160.4.jar -m revanced-integrations-0.96.3.apk -i microg-support -i protobuf-spoof -i client-spoof -i hide-video-ads --exclusive
```

**Comment by KindlyOnes** [comment]
> Hey, I was testing and debugging the patches to add support for Android 5. My changes are in [this repo](https://github.com/d4n3436/revanced-patches-android5). Currently a minimal selection of patches work, like MicroG support, spoof patches and hide video ads. The patched app seems to work fine (at least on an emulator). I tried to make the other patches to work but the current repo layout is confusing to work with because it's outdated from upstream.
> 
> Command I used to patch YouTube:
> 
> ```
> java -jar revanced-cli.jar -a YouTube_16.40.36.apk -o YouTube_ReVanced_16.40.36.apk -b revanced-patches-2.160.4.jar -m revanced-integrations-0.96.3.apk -i microg-support -i protobuf-spoof -i client-spoof -i hide-video-ads --exclusive
> ```

Thank you so much @d4n3436

**Comment by eldepor** [comment]
> Hey, I was testing and debugging the patches to add support for Android 5. My changes are in [this repo](https://github.com/d4n3436/revanced-patches-android5). Currently a minimal selection of patches work, like MicroG support, spoof patches and hide video ads. The patched app seems to work fine (at least on an emulator). I tried to make the other patches to work but the current repo layout is confusing to work with because it's outdated from upstream.
> 
> Command I used to patch YouTube:
> 
> ```
> java -jar revanced-cli.jar -a YouTube_16.40.36.apk -o YouTube_ReVanced_16.40.36.apk -b revanced-patches-2.160.4.jar -m revanced-integrations-0.96.3.apk -i microg-support -i protobuf-spoof -i client-spoof -i hide-video-ads --exclusive
> ```

I literally don't understand how to use this. Where is that CLI? Where to put that Java command? Where to put that youtube apk? where's the output? on PC? I'm completely lost. Can you please give us detailed guide or directly upload the built apk ready and patched? Thanks.

**Comment by eldepor** [comment]
> Hey, I was testing and debugging the patches to add support for Android 5. My changes are in [this repo](https://github.com/d4n3436/revanced-patches-android5). Currently a minimal selection of patches work, like MicroG support, spoof patches and hide video ads. The patched app seems to work fine (at least on an emulator). I tried to make the other patches to work but the current repo layout is confusing to work with because it's outdated from upstream.
> 
> Command I used to patch YouTube:
> 
> ```
> java -jar revanced-cli.jar -a YouTube_16.40.36.apk -o YouTube_ReVanced_16.40.36.apk -b revanced-patches-2.160.4.jar -m revanced-integrations-0.96.3.apk -i microg-support -i protobuf-spoof -i client-spoof -i hide-video-ads --exclusive
> ```

Working nicely so far. Let's see the next hours and days. And please keep it updated man, you are the last hope for us Android 5 users :)). Thanks for not letting us alone.
