### ISSUE TITLE
bug: Live Videos not working

### ISSUE THREAD

**Issue by Syked69** [kitadai31/revanced-patches-android6-7#73]
### Type

Error at runtime

### Bug description

Live videos not working. 

### Steps to reproduce

Try to play any live videos. 

### Device Environment

Android 6.0.1, YT 17.34.36 patches and microg  services 0.3.1.4.240913

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] #74
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
fixed in [v2.160.10](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.10)
