### ISSUE TITLE
bug: Not playing the video

### ISSUE THREAD

**Issue by Agoose1** [kitadai31/revanced-patches-android6-7#77]
### Type

Error at runtime

### Bug description

the problem of not playing the video appears again, it stops after 10 seconds, on other occasions the video does not start

### Steps to reproduce

when playing any video

### Device Environment

Nexus 6 
Android 7.1.1 
YT 17.34.36 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
fixed in [v2.160.10](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.10)
