### ISSUE TITLE
bug: Videos stop and keep in charging randomly

### ISSUE THREAD

**Issue by obiwankenobi7** [kitadai31/revanced-patches-android6-7#79]
### Type

Error at runtime

### Bug description

From June 3rd, this  issue got a lot worse. Videos just stop and keep charging. Sometimes closing the video and open it back help but the issue eventually come back.

### Steps to reproduce

It's random playing any videos.

### Device Environment

Android 6.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
Just solved now!

fixed in [v2.160.10](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.10)
