### ISSUE TITLE
bug: History not saved when client spoof is enabled

### ISSUE THREAD

**Issue by ulzimate** [kitadai31/revanced-patches-android6-7#81]
### Type

Error at runtime

### Bug description

Noticed recently that history was not being saved on either of my devices running Revanced.

This issue was noted here https://github.com/ReVanced/revanced-patches/issues/2779 and was fixed here https://github.com/ReVanced/revanced-patches/commit/bcd8b48e70693dac1bfcc0bf4971d6b526065b59

The patch works fine on my Android 12 device. On my Android 7 device, history is only saved when spoof client is disabled, which causes the unspoofed playback issues.

On my Android 7 device, I've uninstalled Revanced Manger 5-7, Revanced Extended, and MicroG, and did a clean reinstall for all three. 

As of 6/16/2024, Revanced Manager states the patches were updated 12 days ago.

### Steps to reproduce

1) Clean install Revanced
2) Turn on spoof client
3) Watch any video
4) Go to history, it is not saved

### Device Environment

Android 7.0

Android security patch June 5, 2018

Kernel version 3.18.35+

Asus Zenpad 3s 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
No, that was another issue of "Spoof player parameter" patch (doesn't exist anymore)
Read the side effects description in the "Spoof client" settings
