### ISSUE TITLE
feat(patch): Add watch history patch

### ISSUE THREAD

**Issue by AykhanUV** [kitadai31/revanced-patches-android6-7#85]
### Application

Youtube

### Issue

Youtube history is not saving even with spoof client off.

### Patch

Rvx added new patch called watch history so can u add it too?

### Motivation

I think this will resolve history not saving bug

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by TheArgentinian** [comment]
History is still broken in v2.160.11  despite the release notes saying it's been fixed.

**Comment by kitadai31** [comment]
> History is still broken in v2.160.11 despite the release notes saying it's been fixed.

Are you using a brand account?
Then turn on history fix setting manually.

**Comment by TheArgentinian** [comment]
> > History is still broken in v2.160.11 despite the release notes saying it's been fixed.
> 
> Are you using a brand account? Then turn on history fix setting manually.

Thank you. I didn't see the setting. It fixed it. But now it doesn't remember where you paused or if you watched the video in full. Videos show up in history as if you only watched the start (short red progress bar)

**Comment by kitadai31** [comment]
yes, please read the settings text
next update solves this issue by new "Spoof stream" patch

btw brand account issue and DNS blocker issue was solved in the latest version, so Watch history patch is not needed. I close this issue.
