### ISSUE TITLE
bug: App crashes after spoofing app version

### ISSUE THREAD

**Issue by AsphaltKoreaWiki** [kitadai31/revanced-patches-android6-7#89]
### Type

Other

### Bug description

If I spoof the app version to 19.16.39 and then run it, the app crashes

### Steps to reproduce

1. Open App
2. A splash screen will appear.
3. The app crashes.

### Device Environment

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
https://github.com/kitadai31/revanced-patches-android6-7/wiki/Spoof-app-version-information
