### ISSUE TITLE
bug: Spoof Client mode iOS doesn't work anymore and No Spoof has issues frequently

### ISSUE THREAD

**Issue by obiwankenobi7** [kitadai31/revanced-patches-android6-7#92]
### Type

Error at runtime

### Bug description

Two weeks ago Spoof Client suddenly stop working at all. When open revanced all content appears with ERROR SERVER 404.
Disabling Spoof Client option only work randomly since videos take long time to charge or pauses to buffering every few minutes.

### Steps to reproduce

1: Open ReVanced with Spoof Client enabled in iOS mode as General option.
2: to check the secong charging/pausing issue just disable Spoofing.

### Additional context

I'm using the recommended YouTube version with the latest patch.

### Device Environment

Android 6.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
Just fixed now!
https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.12

**Comment by obiwankenobi7** [comment]
Thank you!
